name: Build and Publish to PyPI
on:
  push:
    branches:
      - main
      - master
  pull_request: {}

# by default, permissions are read-only, read + write is required for git pushes
permissions:
  contents: write

env:
  # avoid build failures due to flaky pypi
  PIP_DEFAULT_TIMEOUT: 60
  PIP_RETRIES: 5

  DATABASE_HOST: localhost

  # required otherwise github api calls are rate limited
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
        env:
          MISE_ENV: ci
      - uses: iloveitaly/github-action-direnv-load-and-mask@master
      - run: uv sync
      - run: just lint

  # if you want to test across multiple python versions
  matrix-test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13", "3.12", "3.11", "3.10", "3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - run: mise use python@${{ matrix.python-version }}
      - uses: iloveitaly/github-action-direnv-load-and-mask@master
      - run: docker compose up -d --wait
      - run: uv sync
      - name: Make sure the CLI runs properly
        run: uv run ${{ github.event.repository.name }} --help
      - run: uv run pytest

  build-and-publish:
    needs: matrix-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - run: uv sync

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./pyproject.toml"
          version-path: "project.version"
          fallback-version: "0.1.0"
          output-file: "CHANGELOG.md"

      # NOTE must run after versioning otherwise the right version won't be pushed
      - name: Build distribution package
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: uv build

      - name: Publish to PyPI
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: uv publish

      - name: Github Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          # output options: https://github.com/TriPSs/conventional-changelog-action#outputs
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
